### ISSUE TITLE
hpfeeds repository for HosTaGe

### ISSUE THREAD

**Issue by sastry17** [aau-network-security/HosTaGe#12]
Setup a central repository for HosTaGe to publish the attack data. The data gathered must be useful in threat analysis.

**Comment by sastry17** [comment]
@m-vasiloma  Can we setup an hpfeeds repo in Clauudia or HackLab?

**Comment by sastry17** [comment]
Proposed arch for hostage-hpfeeds integration

![hpfeeds](https://user-images.githubusercontent.com/58994291/89021100-451a7f00-d320-11ea-9ab5-bc561028af59.jpg)

**Comment by sastry17** [comment]
Initial testing with hpfeeds library... 

![hpfeeds-test](https://user-images.githubusercontent.com/58994291/89185318-57075680-d59a-11ea-9a4c-4753f0fd76c2.png)

**Comment by sastry17** [comment]
Publisher(in java) and broker(Python) is checked and tested. 
Created repo: https://github.com/sastry17/HosTaGe-hpfeeds

Subscriber to be implemented with MongoDB.

**Comment by sastry17** [comment]
hpfeeds broker setup on the server with MongoDB auth

**Comment by sastry17** [comment]
hpfeeds subscriber is setup on the server

**Comment by sastry17** [comment]
checked with conpot publisher 

![image](https://user-images.githubusercontent.com/58994291/89895886-cefa0000-dbdc-11ea-89ec-f456c0e9412f.png)

**Comment by irinil** [comment]
First test from app in localhost mongo database was successful! 

![image](https://user-images.githubusercontent.com/16364949/90170960-7330a200-dda9-11ea-9bb9-374b43ac0339.png)

**Comment by sastry17** [comment]
repo setup is complete
