### ISSUE TITLE
Add Button-Like ToolBar

### ISSUE THREAD

**Issue by Akash-Ramjyothi** [aau-network-security/HosTaGe#136]
## Feature Request:

Currently, the screen to add a New Profile has two buttons in the ToolBar which are barely visible. Even if they were, they are like Headings rather than Buttons which they actually are. If there was an Improvement made on the UI Component to make it look more like Buttons, it would improve the User Interface.

## Screenshot of Current Screen:
![WhatsApp Image 2021-03-27 at 11 52 55 AM](https://user-images.githubusercontent.com/54114888/112712165-afa5ae00-8ef3-11eb-95eb-7ea34a927329.jpeg)

**Comment by zafodB** [comment]
Addressed in #202
