### ISSUE TITLE
External IP not shown

### ISSUE THREAD

**Issue by sastry17** [aau-network-security/HosTaGe#15]
The external IP of the honeypot is not shown in the details window. It shows up as blank
![external_ip_bug](https://user-images.githubusercontent.com/58994291/82873083-43a19480-9f34-11ea-9d14-4c3540862b60.jpeg)

**Comment by irinil** [comment]
Issue is now fixed.
The previous IP API doesn't work anymore, so I replaced it with the https://www.ipify.org/ that is free.

![2020-07-01 17_11_37-Android Emulator - Nexus_5X_API_25_5554](https://user-images.githubusercontent.com/16364949/86255282-98819c00-bbbf-11ea-8d1d-26490c5c8e84.png)

**Comment by sastry17** [comment]
Issue is fixed.
