### ISSUE TITLE
All attacks show up as "Internal Attack"

### ISSUE THREAD

**Issue by sastry17** [aau-network-security/HosTaGe#16]
In the attack records information screen, all attacks are categorized as "Internal Attacks" although the attacks are from an External IP. 

![Internal-Attack](https://user-images.githubusercontent.com/58994291/82873374-b0b52a00-9f34-11ea-8794-b8f7249d373c.jpeg)

**Comment by irinil** [comment]
Ok I will look up to it!

**Comment by irinil** [comment]
@sastry17 Also in which pull request was this bug discovered?

**Comment by sastry17** [comment]
Tested. External attacks are now shown as external attacks.
