### ISSUE TITLE
Add limit and offset for Records-Data Pagination

### ISSUE THREAD

**Issue by irinil** [aau-network-security/HosTaGe#41]
All records are fetched when we want to access them. We should fetch them as pages with max 150 records (or what the screen fits) and when the user scrolls then bring the next ones. This will fix the lag of the app for 5000 records and above.

**Comment by sastry17** [comment]
Some issues with Pagination. Attached testing video in Teams

**Comment by sastry17** [comment]
Hi @irinil 

the testing video is on teams
