### ISSUE TITLE
Error in MySQL wrapPacket()

### ISSUE THREAD

**Issue by irinil** [aau-network-security/HosTaGe#5]
This error happens when a discovered attack from MySQl port (from a ping) is logged. I have not found the root cause yet, although this issue does not affect the log record.
 
![error](https://user-images.githubusercontent.com/16364949/81850288-73c65c00-9560-11ea-8bc3-ab6bd1d19b77.png)

**Comment by sastry17** [comment]
Issue fixed by @irinil . There is no error with wrapPacket()
