### ISSUE TITLE
UI: About page

### ISSUE THREAD

**Issue by m-vasiloma** [aau-network-security/HosTaGe#55]
- remove names, 

- add github link, 

- qr code of link, 

- add gsoc logo, 

- version number appears twice now

**Comment by irinil** [comment]
Hello @m-vasiloma ,

With "remove names" what do you mean?

**Comment by m-vasiloma** [comment]
Hi @irinil , I mean remove all developers names' and instead have a link to our git. In the git we will have a comprehensive list of authors, developers and contributors  (we can have a dedicated contributors.md file such as e.g. https://github.com/tklab-tud/ID2T/blob/master/CONTRIBUTORS.md). The problem is that currently it has a few names but many are missing (and it will not look nice with all names in). Hope this is more clear now?

**Comment by irinil** [comment]
> 
> 
> Hi @irinil , I mean remove all developers names' and instead have a link to our git. In the git we will have a comprehensive list of authors, developers and contributors (we can have a dedicated contributors.md file such as e.g. https://github.com/tklab-tud/ID2T/blob/master/CONTRIBUTORS.md). The problem is that currently it has a few names but many are missing (and it will not look nice with all names in). Hope this is more clear now?

Yes thank you!

**Comment by sastry17** [comment]
The about fragment has been updated.
