### ISSUE TITLE
MQTT does not listen on External IP

### ISSUE THREAD

**Issue by sastry17** [aau-network-security/HosTaGe#58]
MQTT currently binds to local ip. Must be  extended to listen on external IP as well.

**Comment by irinil** [comment]
Hello @sastry17 ! I was able to access the config file of the moquette library and now I can change the default IP Address and port programmatically. I created the needed methods in the MQTT class, and you can change them yourself, modifying the following variables:

![image](https://user-images.githubusercontent.com/16364949/87292374-664e3380-c509-11ea-80e9-f7940837d153.png)

Do you want me to add this feature in the User Interface? I am not sure where to add it though.

**Comment by sastry17** [comment]
Hi @irinil 

That is good. I would suggest to keep the port with default 1833 and if possible, try adding the listener configuration to 0.0.0.0 is the config file. Ex: listener 1883 0.0.0.0

Try this and let me know if it works.

**Comment by irinil** [comment]
> 
> 
> Hi @irinil
> 
> That is good. I would suggest to keep the port with default 1833 and if possible, try adding the listener configuration to 0.0.0.0 in the config file. Ex: listener 1883 0.0.0.0
> 
> Try this and let me know if it works.

Yes I have test it with this configuration and works. I also tested with a different IP and port and still works.

**Comment by sastry17** [comment]
MQTT now listens on external IP.
