### ISSUE TITLE
Bind services Rooted Devices Problem

### ISSUE THREAD

**Issue by irinil** [aau-network-security/HosTaGe#62]
The services couldn't listen to default ports on rooted devices.

**Comment by irinil** [comment]
You can now access the ip in MyServerSocketFactory class using the variable ipAddress.

![image](https://user-images.githubusercontent.com/16364949/87776183-0b317f00-c830-11ea-9ee5-81612a06bcce.png)

**Comment by sastry17** [comment]
Issue is fixed with iptables command
