### ISSUE TITLE
PS: remove iptables status text on the settings menu

### ISSUE THREAD

**Issue by sastry17** [aau-network-security/HosTaGe#91]
Play Store version: Remove the status text for the "Iptables available" in the settings menu

**Comment by sastry17** [comment]
remove this:

![image](https://user-images.githubusercontent.com/58994291/91287764-7015b880-e790-11ea-8007-cfaaee6ee632.png)

**Comment by irinil** [comment]
Ok!

**Comment by sastry17** [comment]
text is removed
