### ISSUE TITLE
Location access - Permission to access location - Allow all the time is missing

### ISSUE THREAD

**Issue by sastry17** [aau-network-security/HosTaGe#98]
When the app launches after installation, the permission to access location provides only 2 options - to access the location only when the app is in use or to deny access. There is no option to allow access all the time. 

https://developer.android.com/preview/privacy/location provides information of using _getBackgroundPermissionOptionLabel()_ for asking user permission to access location all the time.

**Comment by irinil** [comment]
Is that only for Android 11?

**Comment by sastry17** [comment]
i think so, may be if we change ACCESS_FINE_LOCATION to ACCESS_BACKGROUND_LOCATION we can enable allow all the time

**Comment by sastry17** [comment]
https://developer.android.com/training/location/permissions#foreground

**Comment by irinil** [comment]
I think for the previous, versions is ok. Or you had problems with location when you left the app on the background?

**Comment by sastry17** [comment]
no the issues occurred when I installed the app from play store. After the app is signed from google, the location permissions show only 2 options.

**Comment by sastry17** [comment]
The issue occurs for Android 10. The quick fix is to add the ACCESS_BACKGROUND_LOCATION to the permissions. I will add it and test.

**Comment by sastry17** [comment]
ok it works now but have to manually enable access all the time. An additional toast is required to remind user to do it.

![location](https://user-images.githubusercontent.com/58994291/91732337-659c5a00-eba8-11ea-88b7-45e41c06b7b4.jpeg)

**Comment by sastry17** [comment]
issue resolved with pr #99
